# Generated by Django 4.2.30 on 2026-08-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_add_hnsw_index_on_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('ready', 'Ready'), ('partial_failure', 'Partial Failure'), ('failed', 'Failed')], default='uploaded', max_length=20),
        ),
    ]
