# Generated by Django 4.2.30 on 2026-08-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='embedding_error',
            field=models.TextField(blank=True, default=''),
        ),
    ]
